spring:
  application:
    name: eureka-server

server:
  port: 9102

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/


