server:
  port: 9102

spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
